# -----------------------
# Copyright (c) 2017, Korbinian Breinl
# All rights reserved.
#
# Model parameter file S-MOF
# -----------------------

wind    :   30
nn       :   7
historical  : on
int_rain: adv
int_temp: adv
